### ISSUE TITLE
MonadBaseControl

### ISSUE THREAD

**Issue by echatav** [michaelt/streaming#12]
Hi, I'm trying to stream rows from postgresql databases using the [postgresl-simple library](https://hackage.haskell.org/package/postgresql-simple). Specifically, there's a [forEach](https://hackage.haskell.org/package/postgresql-simple-0.5.1.2/docs/Database-PostgreSQL-Simple.html#g:17) function. The problem is that it's a CPS calculation in IO. What I want to be able to do is:

``` haskell
streamRows :: (PG.ToRow q, PG.FromRow r) => PG.Connection -> PG.Query -> q -> Stream (Of r) IO ()
streamRows conn query params = liftBaseOp (PG.forEach conn query params) S.yield
```

which gives the type error

``` haskell
        Couldn't match type ‘StM (Stream (Of r) IO) ()’ with ‘()’
        Expected type: (r -> IO (StM (Stream (Of r) IO) ()))
                       -> IO (StM (Stream (Of r) IO) ())
          Actual type: (r -> IO ()) -> IO ()
        Relevant bindings include
          streamRows :: PG.Connection -> PG.Query -> q -> Stream (Of r) IO ()
        In the first argument of ‘liftBaseOp’, namely
          ‘(PG.forEach conn query params)’
        In the expression:
          liftBaseOp (PG.forEach conn query params) S.yield
```

because there is no `instance MonadBaseControl m (Stream f m)`. Would it be possible to construct this instance? If not is there a way around this problem? Thanks.

edit1:
P.S. I realize that it would conflict with the current `MonadBase` instance, but is there another reason?
edit2:
P.P.S. On second thought it wouldn't conflict with the `MonadBase` instance since there's an `instance MonadBase IO IO`. We'd just need `instance MonadBaseControl b m => MonadBaseControl b (Stream f m)` instead of what I wrote above.

**Comment by michaelt** [comment]
I'm not in a position to test `postgresql-simple` at the moment, but looking through the types I wondered how the conduit / persistent material does it, but then chanced on `pipes-postgresql-simple`. There [at the bottom](https://hackage.haskell.org/package/pipes-postgresql-simple-0.1.2.0/docs/src/Pipes-PostgreSQL-Simple.html) Oliver Charles makes a detour via `pipes-concurrency` using this clever helper, which took me by surprise. (I am translating to use `Stream (Of a)` instead of `Producer a`):

```
produceIO
  :: MonadIO m
  => ((a -> IO ()) -> IO ()) -- ^ This action will be called once. It takes
                             -- a function that “yields” an @a@ when called.
  -> Stream (Of a) m ()
produceIO f = do
    (o, i, seal) <- liftIO $ PC.spawn' (PC.bounded 1)
    worker <- liftIO $ Async.async $ do
        f $ \a -> void $ STM.atomically $ PC.send o a
        STM.atomically seal
    liftIO $ Async.link worker
    let loop = do
        ma <- liftIO $ STM.atomically $ PC.recv i
        case ma of
            Nothing -> return ()
            Just a  -> do
                S.yield a
                loop
    loop
```

This is effectively a complicated use of a `Control.Concurrent.STM.TBQueue.TBQueue`. One could probably simplify out the use of `pipes-concurrency`, though I think the main `Input` `Output` and `Buffer` types are very clear (they could easily have been made independent of the Pipes application of them.)  

In any case using `ocharles`'s  approach, we have a sort of bounded queue (limited to length 1); we then give `PG.fold` the action of writing to it (it looks like one could as well use `PG.forEach`). This is the action

```
 \_ a -> STM.atomically (PC.send o a) >> return ()
```

below. Meanwhile we unfold the stream by reading from the other end; this is `loop` below. 

Anyway, using `bounded`, `spawn` and `recv` from `Pipes.Concurrency`, the whole thing can be summed up for our purposes like so:

```
import qualified Control.Concurrent.Async as Async
import qualified Control.Concurrent.STM as STM
import qualified Database.PostgreSQL.Simple as PG
import qualified Pipes.Concurrent as PC
import Streaming
import qualified Streaming.Prelude as S

streamRows :: (PG.ToRow params, PG.FromRow a, MonadIO m) =>
   PG.Connection -> PG.Query -> params -> Stream (Of a) m ()
streamRows c q p =  do
    (o, i, seal) <- liftIO $ PC.spawn' (PC.bounded 1)
    worker <- liftIO $ Async.async $ do
        PG.fold c q p () $ \_ a -> STM.atomically (PC.send o a) >> return ()
        STM.atomically seal
    liftIO (Async.link worker)
    let loop = do
        ma <- liftIO $ STM.atomically $ PC.recv i
        case ma of
            Nothing -> return ()
            Just a  -> do
                S.yield a
                loop
    loop
```

This is just `query` from `pipes-postgresql-simple`.  I will look into it more but does that seem like it works as something to start reasoning from?

**Comment by echatav** [comment]
Cool. It makes sense. I just don't know why use a TBQueue instead of say a TMVar since it's length 1. Anyway, I'll have to give this a think. Thanks so much!

**Comment by michaelt** [comment]
Right, that's part of what I was wondering, it seems unnecessarily elaborate, but the main idea is clear enough I think.  `Pipes.Concurrency` used to use `TMVar` for the `Single` case, and still permits this, but gives a warning, telling you to use `bounded 1` (i.e. a short queue), so I guess he plans on phasing it out. The other question is whether the elaborate framing `pipes-concurrency` uses with `mkWeakTVar`, and so on, is needed for this simple case. I think it is mostly aimed at fancier uses.

**Comment by echatav** [comment]
Yeah, do you think having a `MonadBaseControl` instance would be unfeasible?

**Comment by echatav** [comment]
FWIW, here's a simplified version using `stm` without incurring a `pipes` dependency. Tell me if you see anything obviously wrong but it seems to work for me. Like will `S.take` do the right thing? It doesn't seem like it would terminate the `forEach` early :-/

``` haskell
streamRows
  :: (PG.ToRow params, PG.FromRow a, MonadIO m)
  => PG.Connection -> PG.Query -> params -> Stream (Of a) m ()
streamRows c q p =  do
  isDone <- liftIO $ newTVarIO False
  rowVar <- liftIO $ newEmptyTMVarIO
  liftIO . void . forkIO $ do
    PG.forEach c q p $ atomically . putTMVar rowVar
    atomically $ writeTVar isDone True
  let
    loop = do
      row <- liftIO $ atomically $ takeTMVar rowVar
      S.yield row
      done <- liftIO $ readTVarIO isDone
      unless done loop
  loop
```

**Comment by mitchellwrosen** [comment]
> Yeah, do you think having a MonadBaseControl instance would be unfeasible?

@echatav See the thread at https://github.com/ekmett/free/pull/20 where @jwiegley concluded that the instance is unsound. Well, the instance he came up with anyway.

Perhaps there could be instances like:

``` haskell
instance MonadTransUnlift t => MonadTransControl (Stream f t)
instance MonadBaseUnlift b m => MonadBaseControl b (Stream f m)
```

which sort of punts on the inner monadic state problem, although `Stream` would carry some monadic state of its _own_, so these instances might be unsound as well.

**Comment by echatav** [comment]
@mitchellwrosen Yeah, I concluded that this was unsound for similar reasons.
